version: '3.10'

services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=products
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1031
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    container_name: candleaf
    build:
      context: .
      dockerfile: Dockerfile

    command: sh -c "python /usr/src/candleaf/manage.py migrate --noinput &&
                      python /usr/src/candleaf/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/candleaf/
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: